name: "build ipa dev"

on:
  schedule:
    - cron: '0 0 * * 2' # every Tuesday
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.27.0
          
      - name: Install CocoaPods
        run: |
          sudo gem install securerandom -v 0.3.2
          sudo gem install drb -v 2.0.6 
          sudo gem install activesupport -v 6.1.7.10
          sudo gem install zeitwerk -v 2.6.18 
          sudo gem install activesupport -v 6.1.7.10
          sudo gem install concurrent-ruby -v 1.3.4
          sudo gem install cocoapods

      - name: Install Firebase_CLI
        run: |
          curl -sL https://firebase.tools | bash

      - name: Install XCode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Install iOS SDK
        run: |
          xcodebuild -downloadPlatform iOS

      - name: Install dependencies
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Config Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: ${{ vars.FIREBASE_PROJECT}}
          CI_PLATFORMS: ios
        run: |
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          dart pub global activate flutterfire_cli
          bash lib/core/firebase/flutterfire-config.sh dev
          bash lib/core/firebase/flutterfire-config.sh prod

      - name: Build
        run: |
          flutter build ios --release --no-codesign --flavor dev --dart-define-from-file env/dev.json -t lib/main.dart -v

      - name: Package
        run: |
          cd build/ios
          mv iphoneos Payload
          zip -ro boorusama-dev.ipa Payload

      - name: Upload Artifact
        id: boorusama-ios-latest-upload
        uses: actions/upload-artifact@v4
        with:
          path: |
            ${{ github.workspace }}/build/ios/boorusama-dev.ipa
