name: "*** build ipa file ***"

on:
  schedule:
    - cron: '0 */2 * * *' # every 2 hours
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.5
          
      - name: Install CocoaPods
        run: |
          sudo gem install securerandom -v 0.3.2
          sudo gem install drb -v 2.0.6 
          sudo gem install activesupport -v 6.1.7.10
          sudo gem install zeitwerk -v 2.6.18 
          sudo gem install activesupport -v 6.1.7.10
          sudo gem install cocoapods
          sudo gem uninstall concurrent-ruby
          sudo gem install concurrent-ruby -v 1.3.4

      - name: Install Firebase_CLI
        run: |
          curl -sL https://firebase.tools | bash
          export FIREBASE_TOKEN=1//0eGL6syZXCHS4CgYIARAAGA4SNwF-L9IrfL_bl_AC4Qy18cfG1u6untVarCeMnFDtxSrjqLAQiYbOm23VZEbrkiEytohml6MwGos

      - name: Install XCode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Install iOS SDK
        run: |
          xcodebuild -downloadPlatform iOS

      - name: Install dependencies
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Config Firebase
        run: |
          flutterfire config --project=boorusama-kvan --out=lib/core/firebase/firebase_options_dev.dart --ios-bundle-id=com.degenk.boorusama.dev --ios-out=ios/flavors/dev/GoogleService-Info.plist --macos-bundle-id=com.degenk.boorusama.dev --macos-out=macos/flavors/dev/GoogleService-Info.plist --android-package-name=com.degenk.boorusama.dev --android-out=android/app/src/dev/google-services.json
          flutterfire config --project=boorusama-kvan --out=lib/core/firebase/firebase_options_prod.dart --ios-bundle-id=com.degenk.boorusama --ios-out=ios/flavors/dev/GoogleService-Info.plist --macos-bundle-id=com.degenk.boorusama --macos-out=macos/flavors/dev/GoogleService-Info.plist --android-package-name=com.degenk.boorusama --android-out=android/app/src/dev/google-services.json

      - name: Build
        run: |
          flutter build ios --release --no-codesign --flavor dev --dart-define-from-file env/dev.json -t lib/main.dart -v

      - name: Package
        run: |
          cd build/ios
          mv iphoneos Payload
          zip -ro myapp.ipa Payload

      - name: Upload Artifact
        id: boorusama-ios-latest-upload
        uses: actions/upload-artifact@v4
        with:
          name: myapp.ipa
          path: |
            ${{ github.workspace }}/Application/boorusama.ipa